<#ftl strip_whitespace = true>
<#import "common/common.ftl" as c/>
<@c.page title="Two Factor Authentication Setup">


<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Two Factor Authentication Key</h3>
        </div>
    <form action="/otp/setup/accept-key" method="POST">
        <@c.csrf/>
        <input type="hidden" name="key" value="${keyString}">
        <div class="panel-body">
            <p>Scan the QR Code Into Your Authentication Client and then enter a token generated by it.</>

            <p><img src="/otp/setup/key-image?key=${keyString}" width="300" height="300"/></p>

            <div class="form-group">
                <label for="token">Generated Token</label>
                <input type="text" class="form-control" id="token" name="token" placeholder="123456">
                </div>


            <button type="submit" class="btn btn-default">Confirm</button>
            </div>
        </form>
    </div>

</@c.page>